In [1]:
#-----------------------------#
# Traveling Salesman Problem  #
#-----------------------------#

# Importandoa biblioteca numpy
import numpy as np

# Criando a função para calcular a distância percorrida

def calc_distancia_percorrida (coordenadas, solve_caixeiro) :
  distancia = 0
  # Vamos percorrer a solução dada e vamos calcular a distância percorrida, pautando-se na origem e no destino,
  # de acordo com as matriz de coordenadas
  for i in range( len(solve_caixeiro) - 1 ) :
    origem = solve_caixeiro[i]
    destino = solve_caixeiro[i + 1]
    # Vamos ir somando a distância percorrida, de acordo com a origem e destino
    distancia += coordenadas[origem, destino]

  # Vamos acrescentar para fechar o nosso ciclo, a distância entre a origem e a última cidade visitada
  distancia += coordenadas[solve_caixeiro[-1], solve_caixeiro[0]]

  return distancia

In [2]:
# Vamos receber as instâncias do nosso problema

# Recebendo a Matriz de coordenadas
coordenadas = np.array([[0, 12, 7, 9, 8],
                        [12, 0, 11, 7, 6],
                        [7, 11, 0, 12, 13],
                        [9, 7, 12, 0, 8],
                        [8, 6, 13, 8, 0]])

# Recebendo a Solução
solve_caixeiro = [1, 0, 3, 4, 2]

In [3]:
# Conferindo os dados

# Checkando a matriz de coordenadas
print(coordenadas)

print()

# Verificando a lista de solução
print(solve_caixeiro)

[[ 0 12  7  9  8]
 [12  0 11  7  6]
 [ 7 11  0 12 13]
 [ 9  7 12  0  8]
 [ 8  6 13  8  0]]

[1, 0, 3, 4, 2]


In [4]:
# Vamos calcular a distância percorrida
dist_percorrida = calc_distancia_percorrida (coordenadas, solve_caixeiro)

# Exibindo os dados finais
print(f"Dada a solução : {solve_caixeiro}\nTeremos a Distância Percorrida de : {dist_percorrida}")

Dada a solução : [1, 0, 3, 4, 2]
Teremos a Distância Percorrida de : 53
